# ===============================
# Configurazione principale NAS Monitoring
# ===============================

# URL su cui è esposto Node Exporter (endpoint Prometheus-style)
node_exporter_url: "http://10.8.0.1:9100/metrics"

# Sezione metriche:
# Puoi inserire "all" per raccogliere tutte le metriche disponibili,
# oppure una lista di metriche esatte o pattern regex (es: ^node_cpu_.*_total$)
metrics: "all"

# Configurazione tentativi e delay per retry di operazioni critiche (es: richieste HTTP, RabbitMQ)
retry:
  attempts: 3        # Numero di tentativi
  delay_seconds: 5   # Secondi di attesa tra un tentativo e l'altro

# Soglie di anomalia: se una metrica supera questi valori, viene generato un alert
anomaly_thresholds:
  cpu_usage_percent: 90     # Alert se uso CPU sopra il 90%
  memory_usage_percent: 90  # Alert se uso RAM sopra il 90%
  disk_free_percent: 10     # Alert se spazio disco libero sotto il 10%

# Configurazione MongoDB per la persistenza delle metriche (esempio con Atlas)
mongodb:
  uri: "mongodb+srv://Synology:iHkxxpmW65T2pSly@cluster0.0mucwtd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  database: "nas_metrics_rabbitmq"  # Nome database
  collection_info: "metrics"        # Collection per metriche generali
  collection_warning: "alerts"      # Collection per warning/alert

# Configurazione RabbitMQ per la pubblicazione delle metriche
rabbitmq:
  host: "10.8.0.6"     # Host RabbitMQ
  port: 5672           # Porta
  username: "guest"    # Username
  password: "guest"    # Password
  queue_info: "nas_metrics"    # Coda per metriche generali
  queue_warning: "nas_warnings"  # Coda per warning/alert

# Dettagli Node Exporter (per eventuali usi futuri)
node_exporter:
  host: "10.8.0.1"     # Host su cui gira Node Exporter
  port: 9100           # Porta
  vpn_required: true   # Indica se è necessaria una VPN per raggiungerlo

# Parametri del consumer RabbitMQ
consumer:
  poll_interval_seconds: 30  # Ogni quanti secondi interroga la coda
  log_level: "INFO"          # Livello di log

# Parametri del producer RabbitMQ
producer:
  push_interval_seconds: 60  # Ogni quanti secondi invia metriche
  log_level: "INFO"          # Livello di log

# ===============================
# Aggiungi altre sezioni/configurazioni qui se servono
# ===============================